import Head from 'next/head';
import Image from 'next/image';
import fsPromises from 'fs/promises';
import { useState } from 'react';
import path from 'path';
import Overlay from '../components/Overlay';
import TaskDetail from '../components/TaskDetail';
import BoardContainer from '../components/BoardContainer';
import Header from '../components//Header';
import SideNav from '../components/SideNav';
import NewTask from '../components/NewTask';
import NewBoard from '../components/NewBoard';
import EditBoard from '../components/EditBoard';

export default function Home(props) {
  const [boards, setBoards] = useState(props.boards);
  const [showSideNav, setShowSideNav] = useState(true);
  const [showTaskDetail, setShowTaskDetail] = useState(false);
  const [showAddNewTask, setShowAddNewTask] = useState(false);
  const [showAddNewBoard, setShowAddNewBoard] = useState(false);
  const [showEditBoard, setShowEditBoard] = useState(false);
  const [selectedTask, setSelectedTask] = useState({});
  const [selectedBoard, setSelectedBoard] = useState(boards[0].name);
  const boardNames = boards.map((board) => board.name);

  const toggleSideNav = () => {
    setShowSideNav(!showSideNav);
  };

  const toggleTaskDetail = () => setShowTaskDetail(!showTaskDetail);

  const toggleAddNewTask = () => setShowAddNewTask(!showAddNewTask);

  const toggleAddNewBoard = () => setShowAddNewBoard(!showAddNewBoard);

  const toggleEditBoard = () => setShowEditBoard(!showEditBoard);

  const editBoardHandler = (boardName) => {
    toggleEditBoard();
    setSelectedBoard(boardName);
  };

  const selectBoardHandler = (boardName) => {
    setSelectedBoard(boardName);
  };

  return (
    <div>
      <Head>
        <title>Frontend Mentor | Kanban task management web app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main className=" bg-light-grey h-full relative">
        {showTaskDetail && <Overlay onShowOverlay={toggleTaskDetail} />}
        {showTaskDetail && <TaskDetail selectedTask={selectedTask} />}
        {showAddNewTask && <Overlay onShowOverlay={toggleAddNewTask} />}
        {showAddNewTask && <NewTask />}
        {showAddNewBoard && <Overlay onShowOverlay={toggleAddNewBoard} />}
        {showAddNewBoard && <NewBoard />}
        {showEditBoard && <Overlay onShowOverlay={toggleEditBoard} />}
        {showEditBoard && <EditBoard board={boards[0]} />}
        <Header
          boardName={boards[0].name}
          onShowOverlay={toggleSideNav}
          onShowNewTask={toggleAddNewTask}
        />
        <section className="flex flex-row h-full">
          {showSideNav && (
            <SideNav
              boardNames={boardNames}
              onShowSideNav={toggleSideNav}
              onAddBoard={toggleAddNewBoard}
              onEditBoard={editBoardHandler}
              onSelectBoard={selectBoardHandler}
              selectedBoard={selectedBoard}
            />
          )}

          <BoardContainer
            board={boards[0]}
            onShowOverlay={toggleTaskDetail}
            onSelectedTask={setSelectedTask}
            selectedTask={selectedTask}
          />
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'data.json');
  const jsonData = await fsPromises.readFile(filePath);
  const boards = JSON.parse(jsonData);

  return {
    props: boards,
  };
}
