import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="bg-neutral-500">
      <Head>
        <title>Frontend Mentor | Kanban task management web app</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main>
        <h1>Frontend Mentor</h1>
      </main>
    </div>
  );
}
