import Head from 'next/head';
import Image from 'next/image';
import fsPromises from 'fs/promises';
import { useState } from 'react';
import path from 'path';

import BoardContainer from '../components/BoardContainer';
import Header from '../components//Header';

export default function Home(props) {
  const [boards, setBoards] = useState(props.boards);

  return (
    <div>
      <Head>
        <title>Frontend Mentor | Kanban task management web app</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main className=" bg-light-grey">
        <Header boardName={boards[0].name} />
        <BoardContainer board={boards[0]} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'data.json');
  const jsonData = await fsPromises.readFile(filePath);
  const boards = JSON.parse(jsonData);

  return {
    props: boards,
  };
}
